[package]
name = "eel-nvim-macros"
version = "0.0.2"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
deluxe = "0.5.0"
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = { version = "2.0.111", features = ["full"] }
